spring.application.name: tracing-tracing

server.port: 8080

tracing:
  monitor:
    cassandra:
      servers: localhost
      keyspace: tracing

metrics.puller:
  influxdb:
    url: http://localhost:8086
    database: customer
    username: test
    password: 123

spring.thymeleaf.cache: false